[package]
name = "cryptopals-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
thiserror = "1.0.38"

[dev-dependencies]
anyhow = "1.0.61"
